```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```
# More Resources and Sites for Learning R and Getting Help

This series of workshops will not teach you everything you need to know about R. In fact, I think that might be impossible to lean everything as R is changing and developing at lightning speed every day. _I have been a student and user of R for over 20+ years and learn something new all the time!_ However, these workshops are designed to give you a foundation from which to move forward and become comfortable using R as well as learning how to learn R and where to go for help. Here is an initial list of places to start learning R and getting help.

### Learning R

* [Code School - TRYR](http://tryr.codeschool.com/)
    + **DO THIS FIRST** Code School is an online learning environment. The **TRYR** site is completely free and is a great place to start learning r. You don't even need to have the R software installed! I highly encourage you to run through at least module 1 - but the more you complete, the better!
* [Data Camp](https://www.datacamp.com/)
    + DataCamp is another great place to start learning online. You need to create an account to get started. There are many FREE courses available on R.
* [RStudio Online Learning](https://www.rstudio.com/resources/training/online-learning/)
    + RStudio also provides a wealth of tutorials, articles, and examples exist to help you learn R and its extensions.
* [UCLA Institute for Digital Research and Education (IDRE)](http://www.ats.ucla.edu/stat/r/)
    + The IDRE by UCLA is an excellent source for help with many statistical software pages and analyses including R.
* [SWIRL](http://swirlstats.com/)
    + `swirl` is actually an R package you install from within R. `swirl` teaches you R programming and data science interactively, at your own pace, and right in the R console!
* [Quick-R](http://www.statmethods.net/index.html)
    + This is an excellent site for quick help and resources for using R and statistical analyses in general. The site is owned and maintained by Rob Kabacoff, who also authored the very good book "R in Action".

### Getting Help

The websites listed below all provide information on how to get help in R.

* [Quick-R Help](http://www.statmethods.net/interface/help.html)
* ["How to ask for R help" blog post](http://blog.revolutionanalytics.com/2014/01/how-to-ask-for-r-help.html)
* [R-help mailing list](https://stat.ethz.ch/mailman/listinfo/r-help)
* [R Section of StackOverflow](http://stackoverflow.com/questions/tagged/r)

