```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```
# Information on R

The links provided below are useful to review as you prepare to learn and use R. 

### Information on R

Learn more about the free R software at the "R-Project for Statistical Computing."

* [The R Project](https://www.r-project.org/)
* [About R](https://www.r-project.org/about.html)
* [The R Foundation](https://www.r-project.org/foundation/)

  
### R Documentation

The "Comprehensive R Archive Network"" or CRAN is the site for obtaining the R software. This site is a collection of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R. CRAN also maintains 7000+ packages which provide additional functions and capabilities beyond the base software.

* [Manuals](https://cran.r-project.org/manuals.html )
* [FAQs](https://cran.r-project.org/faqs.html)


### The R Journal, Books and Other Resources

There are literally thousands of sites around the world providing information, tips, help, and insights into programming, statistics and data analysis with R. The links below are just a few to get you started.

* [The Journal of Statistical Software (JSS)](http://www.jstatsoft.org/)
    + The JSS was established in 1996, the Journal of Statistical Software publishes articles, book reviews, code snippets, and software reviews on the subject of statistical software and algorithms. The contents are freely available on-line.
* [The R Journal](https://journal.r-project.org/)
    + The R Journal is the open access, refereed journal of the R project for statistical computing. It features short to medium length articles covering topics that might be of interest to users or developers of R, including: add-on packages, programming hints, help tips for beginners, and demonstrations of new or existing techniques used for new and interesting applications.
* [Books](https://www.r-project.org/doc/bib/R-books.html)
    + This website gives a partially annotated list of books that are related to S or R and may be useful to the R user community.
* [Bioconductor](https://www.bioconductor.org/)
    + Another key user community and developer of R packages and resources is Bioconductor. Bioconductor provides tools for the analysis and comprehension of high-throughput genomic data. Bioconductor uses the R statistical programming language, and is open source and open development.

