```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here


# end setup chunk
```
# How to Install R

### Download then install the software

1. Getting the Software
    + Go to the CRAN homepage at https://cran.r-project.org/ 
2. Download and Installing R 
    + Look in the box at the TOP of the CRAN homepage
    + For [Windows](https://cran.r-project.org/bin/windows/) - click on the link for "BASE" and then download the current version of R. I would suggest installing the 64-bit version as appropriate for your operating system.
    + for [Mac](https://cran.r-project.org/bin/macosx/) - read through the specifics to see which package (PKG) is best for your operating system version.
    + NOTE: If you are interested in further development using R, like building your own packages, you may also be interested in downloading and installing Rtools (windows) or tools (Mac).

### Other Sources for Help Installing R

* The Institute for Digital Research and Education at UCLA also has information and instructions for [Installing, Customizing and Updating R](http://www.ats.ucla.edu/stat/r/icu/) with details for both Windows and Mac operating systems.
* There is also helpful information at the [RStudio online learning website](https://www.rstudio.com/resources/training/online-learning/). 
